// Generated by CoffeeScript 1.3.0
(function() {
  var Emitter, Stateful, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  Emitter = require('common-emitter');

  _ = require('underscore');

  Stateful = (function(_super) {

    __extends(Stateful, _super);

    Stateful.name = 'Stateful';

    Stateful.define = function(name, config) {
      return Object.defineProperty(this.prototype, name, config);
    };

    Stateful.define('statechart', {
      get: function() {
        return this.__statechart;
      }
    });

    Stateful.define('stateName', {
      get: function() {
        return this.__state.name;
      }
    });

    Stateful.define('state', {
      get: function() {
        return this.__state;
      },
      set: function(obj) {
        return this.__state = obj;
      }
    });

    Stateful.Success = function() {
      return false;
    };

    Stateful.Failure = function() {
      return true;
    };

    Stateful.StateChart = function(chart) {
      var addPaths;
      this.prototype.__statechart = {};
      addPaths = function(statesObj, parent) {
        var defn, name, stateObj, _results;
        _results = [];
        for (name in statesObj) {
          defn = statesObj[name];
          stateObj = {
            name: name,
            transitions: defn.transitions,
            methods: defn.methods,
            paths: {}
          };
          parent[name] = stateObj;
          _results.push(addPaths(defn.paths, stateObj.paths));
        }
        return _results;
      };
      return addPaths(chart, this.prototype.__statechart);
    };

    function Stateful(config) {
      var stateName;
      if (this.statechart == null) {
        return;
      }
      stateName = _.keys(this.statechart)[0];
      this.setState(this.statechart[stateName]);
    }

    Stateful.prototype.dispose = function() {
      return this.removeAllListeners();
    };

    Stateful.prototype.setState = function(stateObj) {
      var oldState;
      if (this.state) {
        oldState = this.state;
        this.removeMethods(oldState.methods);
      }
      this.state = stateObj;
      this.addMethods(this.state.methods);
      this.buildTransitions(this.state.transitions);
      this.onStateChange(this.state, oldState);
      this.emit('statechange', this.stateName, oldState != null ? oldState.name : void 0);
      return this.emit("statechange:" + this.stateName, oldState != null ? oldState.name : void 0);
    };

    Stateful.prototype.onStateChange = function(newStateObj, oldStateObj) {};

    Stateful.prototype.removeMethods = function(methods) {
      var method, _results;
      if (methods == null) {
        return;
      }
      _results = [];
      for (method in methods) {
        if (this[method] != null) {
          delete this[method];
        }
        if (this["_" + method] != null) {
          _results.push(this[method] = this["_" + method]);
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Stateful.prototype.addMethods = function(methods) {
      var impl, method, _results;
      if (methods == null) {
        return;
      }
      _results = [];
      for (method in methods) {
        impl = methods[method];
        if (this[method] != null) {
          this["_" + method] = this[method];
        }
        _results.push(this[method] = impl);
      }
      return _results;
    };

    Stateful.prototype.buildTransitions = function(transitions) {
      var chgMethod, destination, t, _i, _len, _results,
        _this = this;
      _results = [];
      for (_i = 0, _len = transitions.length; _i < _len; _i++) {
        t = transitions[_i];
        destination = this.pathResolver(t.destination);
        chgMethod = this[t.action];
        _results.push(this[t.action] = function() {
          var dontTransition;
          dontTransition = (chgMethod.apply(_this, arguments))();
          if (!dontTransition) {
            return _this.setState(destination);
          }
        });
      }
      return _results;
    };

    Stateful.prototype.pathResolver = function(path) {
      var step, steps, target, _i, _len;
      steps = path.split('/');
      target = {
        paths: this.statechart
      };
      for (_i = 0, _len = steps.length; _i < _len; _i++) {
        step = steps[_i];
        target = target.paths[step];
      }
      return target;
    };

    return Stateful;

  })(Emitter);

  module.exports = Stateful;

}).call(this);
